spring:
  application:
    name: git-internals-explorer-api

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/git_explorer
    username: git_explorer
    password: git_explorer

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false